# action.yml
name: sigstore-git-verifier
description: 'Verify that latest commit is present in the sigstore transparency log'
runs:
  using: "composite"
  steps:
    - run: bash -c "env | sort"
      shell: bash
    - run: cat $GITHUB_EVENT_PATH
      shell: bash
    - run: go install github.com/sigstore/rekor/cmd/rekor-cli@main
      shell: bash
    - run: |
        if [[ $GITHUB_EVENT_NAME == "pull_request" ]]
        then
          commit=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.base.sha)
        else
          commit=$GITHUB_SHA
        fi

        echo "Verifying commit: $commit"
        uuid=$(rekor-cli search --artifact <(echo $commit) | tail -n 1)
        sig=$(rekor-cli get --uuid=$uuid --format=json | jq -r .Body.RekordObj.signature.content)
        cosign verify-blob -key $GITHUB_WORKSPACE/cosign.pub -signature <(echo $sig) <(echo $commit)
      shell: bash
