# action.yml
name: sigstore-git-verifier
description: 'Verify that latest commit is present in the sigstore transparency log'
runs:
  using: "composite"
  steps:
    - run: go install github.com/sigstore/rekor/cmd/rekor-cli@main
      shell: bash
    - run: |
        echo "Verifying commit: $GITHUB_SHA"
        uuid=$(rekor-cli search --artifact <(echo $GITHUB_SHA) | tail -n 1)
        sig=$(rekor-cli get --uuid=$uuid --format=json | jq -r .Body.RekordObj.signature.content)
        cosign verify-blob -key $GITHUB_WORKSPACE/cosign.pub -signature <(echo $sig) <(echo $GITHUB_SHA)
      shell: bash
