#!/bin/bash

if [ -z ${COSIGN_PASSWORD+x} ]
then
    echo "COSIGN_PASSWORD is unset; set it to sign commits with export COSIGN_PASSWORD=***" && exit 1
fi

if [ -e $(git rev-parse --show-toplevel)/cosign.key ] && [ -e $(git rev-parse --show-toplevel)/cosign.pub ]
then
    echo "Cosign key pair found"
else
    echo "Cosign key pair not found; generate a key pair with cosign generate-key-pair" && exit 1
fi

echo -n $COSIGN_PASSWORD | COSIGN_EXPERIMENTAL=1 cosign sign-blob -key $(git rev-parse --show-toplevel)/cosign.key <(git rev-parse HEAD)
