name: sigstore-git-verifier
on: [push, pull_request, pull_request_target, workflow_dispatch]

jobs:
  verify-commit:
    runs-on: ubuntu-latest
    name: Verify latest commit is in tlog
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v0.1.0'
      - name: Verify latest commit is in tlog
        uses: mbestavros/sigstore-git-verifier@main
